version: "3.6"

services:
  client:
    container_name: client
    build: ./client
    ports:
      - 7000:80
    volumes:
      - ./client:/usr/src/app
    environment:
      - MULTIMASK_ENV=dev
  api:
    container_name: api
    build: ./api
    ports:
      - 8000:8000
    environment:
      - MULTIMASK_ENV=dev
  proxy:
    container_name: proxy
    build: ./proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - client
      - api
    volumes:
      - ./client:/var/lib/src/app/build
