version: "3.6"

services:
  redis:
    image: redis
  client:
    container_name: client
    build: ./client
    ports:
      - 3000:3000
    environment:
      - MULTIMASK_ENV=dev
    labels:
      - "traefik.port=3000"
      - "traefik.backend=client"
      - "traefik.frontend.rule=PathPrefixStrip:/"
  api:
    container_name: api
    build: ./api
    ports:
      - 8000:8000
    environment:
      - MULTIMASK_ENV=dev
    labels:
      - "traefik.backend=api"
      - "traefik.port=8000"
      - "traefik.frontend.rule=PathPrefixStrip:/api"
    links:
      - "redis:redis"
  traefik:
    image: traefik
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
